'''List of features'''
FEATURES = [
    ['1', 'OutlookIntegration', 'Enables Outlook integration.'],
    ['2', 'ListenIn', 'Enables call listen in.'],
    ['3', 'Recording', 'Enables call recording.'],
    ['4', 'LogonWithDevice', 'LogonWithDevice'],
    ['5', 'QueuePriority', 'Enables queue priority.'],
    ['6', 'CallPickup', 'Enables call pick up.'],
    ['7', 'Wave', 'Enables Zisson Wave.'],
    ['8', 'WavePlus', 'Enables Zisson Wave Plus.'],
    ['9', 'SmsPopup', 'Enables SMS pop up.'],
    ['10', 'Conference', 'Enables telephone conferencing.'],
    ['11', 'ChargeMobilePhone', 'NULL'],
    ['12', 'MultiLocation', 'Enables multiple/selectable locations for logins.'],
    ['13', 'TfxLogging', 'Enables or disables sending events to traffix for a given customer.'],
    ['14', 'WaveConsole', 'Enables wave console'],
    ['15', 'Dashboard', 'Enables wave dashborad.'],
    ['16', 'Reports', 'Enables statistical reports.'],
    ['17', 'WallBoard', 'None'],
    ['18', 'WallboardAnswerRate', 'Enables answer rate on the wallboard'],
    ['19', 'SearchClearOnIncoming', 'None'],
    ['20', 'FixedNumber', 'Enables fixed numbers'],
    ['21', 'QueueCallPickup', 'Enables picking call from queues'],
    ['22', 'Bladcentralen', 'popup_link'],
    ['23', 'ExternalNumberLogonAvailable', 'None'],
    ['24', 'CustomerAdministrator', 'Customer Administrator'],
    ['25', 'OperatorAdministrator', 'Operator Administrator'],
    ['26', 'PauseAdminEnabled', 'Enable administration of pause flags'],
    ['27', 'CallbackAdminEnabled', 'Enable administration of callback flags'],
    ['28', 'GroupsAdminEnabled', 'Enable administration of groups'],
    ['29', 'AgentOverview', 'Agent Overview'],
    ['31', 'RippleNotification', 'pop up'],
    ['32', 'InstantMessaging', 'InstantMessaging'],
    ['33', 'RecordSelf', 'Enables call recording of self'],
    ['34', 'PhotoButton', 'None'],
    ['35', 'UsePsWinCom', 'None'],
    ['36', 'QueuePriorityVisible', 'QueuePriorityVisible'],
    ['37', 'CiscoSpaAdvancedMenus', 'Advanced functionality on Cisco phones'],
    ['38', 'AgentReports', 'None'],
    ['39', 'VirtualQueues', 'None'],
    ['40', 'BrowserRestoreOnIncomingCall', 'None'],
    ['41', 'ExternalDirectoryService', 'None'],
    ['42', 'Statistics', 'None'],
    ['43', 'CallerHistory', 'None'],
    ['44', 'RecordingToFTP', 'None'],
    ['45', 'GroupFilter', 'None'],
    ['46', 'AccumulativeQueueWaitTime', 'None'],
    ['47', 'BedriftsvarStatistics', 'None'],
    ['48', 'PacketCapture', 'Enable packet capture of data streams'],
    ['49', 'AgentMonitor', 'Enable agent monitor in Wave'],
    ['51', 'NumberlistAdmin', 'None'],
    ['52', 'ExchangeIntegration', 'None'],
    ['53', 'ZissonIpPabx', 'None'],
    ['54', 'SetOutgoingNumberFromWave', 'None'],
    ['55', 'QueueEnquiry', 'None'],
    ['56', 'LyncClientIntegration', 'None'],
    ['57', 'ServiceNumberGroupFilter', 'None'],
    ['58', 'ButtonBottomNote', 'None'],
    ['59', 'AsternicStatistics', 'None'],
    ['60', 'SmsChat', 'None'],
    ['61', 'WebChat', 'None'],
    ['62', 'FacebookChat', 'None'],
    ['63', 'WaveEmail', 'None'],
    ['64', 'MessageTab', 'None'],
    ['65', 'MediaArchive', 'None'],
    ['66', 'RecordAllCalls', 'Record all calls'],
    ['67', 'ZissonInternalCustomer', 'Zisson internal customer'],
    ['68', 'CallOutgoingFailedTrigger', 'Call trigger when outgoing calls fail'],
    ['69', 'Switchboard', 'None'],
    ['70', 'RecordAllowedCalls', 'Record all calls which have been allowed by caller consent'],
    ['71', 'JawsIntegration', 'Writes stuff to an INI file'],
    ['72', 'GsmBusyPause', 'Pause agent when receiving busy from GSM'],
    ['74', 'RedirectToLastQueueOnFailure', 'RedirectToLastQueueOnFailure'],
    ['75', 'Bulk', 'SMS	Bulk SMS'],
    ['76', 'Dialer', 'Dialer'],
    ['77', 'Twitter', 'Chat	Twitter Chat'],
    ['78', 'Generic', 'Chat	Generic Chat'],
    ['79', 'TN', 'MBN absence kø	mbn Polycom'],
    ['80', 'Invoice', 'Lager invoicefil pr mnd'],
    ]
