"""empty message

Revision ID: 129995f3c444
Revises: 6d4696a33fd3
Create Date: 2017-04-02 21:55:49.201562

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '129995f3c444'
down_revision = '6d4696a33fd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    CONDITION = (
        ('new', 'ny'),
        ('used', 'brukt'))
    op.add_column('inventory', sa.Column('condition', sqlalchemy_utils.types.choice.ChoiceType(CONDITION), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory', 'condition')
    # ### end Alembic commands ###
